version: '3.7'

services:
    php:
        image: webdevops/php-dev:8.0-alpine
        ports:
            - 9000:9000
        environment:
            PHP_IDE_CONFIG: "serverName=globalis.opusraid.local" # Used for the debugger
